# This code has been automatically generated by:
# dev_scripts/generate_test_for_x_or_default.py
# Do NOT edit or append.


"""Test ``X_or_default`` methods on classes which contain lists."""


# pylint: disable=missing-docstring


import unittest

import tests.common
import tests.common_jsonization


class Test_Extension(unittest.TestCase):
    """
    Test ``X_or_default`` on instances of
    :py:class:`aas_core3_rc02.types.Extension`.
    """

    def test_value_type_or_default_on_complete_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_complete_extension()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "Extension"
            / "on_complete.json"
            / "value_type_or_default.trace"
        )

        log = [tests.common.trace(instance.value_type_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_value_type_or_default_on_minimal_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_minimal_extension()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "Extension"
            / "on_minimal.json"
            / "value_type_or_default.trace"
        )

        log = [tests.common.trace(instance.value_type_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)


class Test_Qualifier(unittest.TestCase):
    """
    Test ``X_or_default`` on instances of
    :py:class:`aas_core3_rc02.types.Qualifier`.
    """

    def test_kind_or_default_on_complete_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_complete_qualifier()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "Qualifier"
            / "on_complete.json"
            / "kind_or_default.trace"
        )

        log = [tests.common.trace(instance.kind_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_kind_or_default_on_minimal_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_minimal_qualifier()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "Qualifier"
            / "on_minimal.json"
            / "kind_or_default.trace"
        )

        log = [tests.common.trace(instance.kind_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)


class Test_Submodel(unittest.TestCase):
    """
    Test ``X_or_default`` on instances of
    :py:class:`aas_core3_rc02.types.Submodel`.
    """

    def test_kind_or_default_on_complete_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_complete_submodel()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "Submodel"
            / "on_complete.json"
            / "kind_or_default.trace"
        )

        log = [tests.common.trace(instance.kind_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_kind_or_default_on_minimal_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_minimal_submodel()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "Submodel"
            / "on_minimal.json"
            / "kind_or_default.trace"
        )

        log = [tests.common.trace(instance.kind_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)


class Test_RelationshipElement(unittest.TestCase):
    """
    Test ``X_or_default`` on instances of
    :py:class:`aas_core3_rc02.types.RelationshipElement`.
    """

    def test_kind_or_default_on_complete_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_complete_relationship_element()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "RelationshipElement"
            / "on_complete.json"
            / "kind_or_default.trace"
        )

        log = [tests.common.trace(instance.kind_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_kind_or_default_on_minimal_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_minimal_relationship_element()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "RelationshipElement"
            / "on_minimal.json"
            / "kind_or_default.trace"
        )

        log = [tests.common.trace(instance.kind_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)


class Test_SubmodelElementList(unittest.TestCase):
    """
    Test ``X_or_default`` on instances of
    :py:class:`aas_core3_rc02.types.SubmodelElementList`.
    """

    def test_kind_or_default_on_complete_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_complete_submodel_element_list()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "SubmodelElementList"
            / "on_complete.json"
            / "kind_or_default.trace"
        )

        log = [tests.common.trace(instance.kind_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_kind_or_default_on_minimal_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_minimal_submodel_element_list()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "SubmodelElementList"
            / "on_minimal.json"
            / "kind_or_default.trace"
        )

        log = [tests.common.trace(instance.kind_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_order_relevant_or_default_on_complete_instance_against_recorded(
        self,
    ) -> None:
        instance = tests.common_jsonization.load_complete_submodel_element_list()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "SubmodelElementList"
            / "on_complete.json"
            / "order_relevant_or_default.trace"
        )

        log = [tests.common.trace(instance.order_relevant_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_order_relevant_or_default_on_minimal_instance_against_recorded(
        self,
    ) -> None:
        instance = tests.common_jsonization.load_minimal_submodel_element_list()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "SubmodelElementList"
            / "on_minimal.json"
            / "order_relevant_or_default.trace"
        )

        log = [tests.common.trace(instance.order_relevant_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)


class Test_SubmodelElementCollection(unittest.TestCase):
    """
    Test ``X_or_default`` on instances of
    :py:class:`aas_core3_rc02.types.SubmodelElementCollection`.
    """

    def test_kind_or_default_on_complete_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_complete_submodel_element_collection()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "SubmodelElementCollection"
            / "on_complete.json"
            / "kind_or_default.trace"
        )

        log = [tests.common.trace(instance.kind_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_kind_or_default_on_minimal_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_minimal_submodel_element_collection()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "SubmodelElementCollection"
            / "on_minimal.json"
            / "kind_or_default.trace"
        )

        log = [tests.common.trace(instance.kind_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)


class Test_Property(unittest.TestCase):
    """
    Test ``X_or_default`` on instances of
    :py:class:`aas_core3_rc02.types.Property`.
    """

    def test_kind_or_default_on_complete_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_complete_property()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "Property"
            / "on_complete.json"
            / "kind_or_default.trace"
        )

        log = [tests.common.trace(instance.kind_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_kind_or_default_on_minimal_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_minimal_property()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "Property"
            / "on_minimal.json"
            / "kind_or_default.trace"
        )

        log = [tests.common.trace(instance.kind_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_category_or_default_on_complete_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_complete_property()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "Property"
            / "on_complete.json"
            / "category_or_default.trace"
        )

        log = [tests.common.trace(instance.category_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_category_or_default_on_minimal_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_minimal_property()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "Property"
            / "on_minimal.json"
            / "category_or_default.trace"
        )

        log = [tests.common.trace(instance.category_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)


class Test_MultiLanguageProperty(unittest.TestCase):
    """
    Test ``X_or_default`` on instances of
    :py:class:`aas_core3_rc02.types.MultiLanguageProperty`.
    """

    def test_kind_or_default_on_complete_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_complete_multi_language_property()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "MultiLanguageProperty"
            / "on_complete.json"
            / "kind_or_default.trace"
        )

        log = [tests.common.trace(instance.kind_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_kind_or_default_on_minimal_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_minimal_multi_language_property()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "MultiLanguageProperty"
            / "on_minimal.json"
            / "kind_or_default.trace"
        )

        log = [tests.common.trace(instance.kind_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_category_or_default_on_complete_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_complete_multi_language_property()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "MultiLanguageProperty"
            / "on_complete.json"
            / "category_or_default.trace"
        )

        log = [tests.common.trace(instance.category_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_category_or_default_on_minimal_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_minimal_multi_language_property()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "MultiLanguageProperty"
            / "on_minimal.json"
            / "category_or_default.trace"
        )

        log = [tests.common.trace(instance.category_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)


class Test_Range(unittest.TestCase):
    """
    Test ``X_or_default`` on instances of
    :py:class:`aas_core3_rc02.types.Range`.
    """

    def test_kind_or_default_on_complete_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_complete_range()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "Range"
            / "on_complete.json"
            / "kind_or_default.trace"
        )

        log = [tests.common.trace(instance.kind_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_kind_or_default_on_minimal_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_minimal_range()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "Range"
            / "on_minimal.json"
            / "kind_or_default.trace"
        )

        log = [tests.common.trace(instance.kind_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_category_or_default_on_complete_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_complete_range()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "Range"
            / "on_complete.json"
            / "category_or_default.trace"
        )

        log = [tests.common.trace(instance.category_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_category_or_default_on_minimal_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_minimal_range()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "Range"
            / "on_minimal.json"
            / "category_or_default.trace"
        )

        log = [tests.common.trace(instance.category_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)


class Test_ReferenceElement(unittest.TestCase):
    """
    Test ``X_or_default`` on instances of
    :py:class:`aas_core3_rc02.types.ReferenceElement`.
    """

    def test_kind_or_default_on_complete_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_complete_reference_element()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "ReferenceElement"
            / "on_complete.json"
            / "kind_or_default.trace"
        )

        log = [tests.common.trace(instance.kind_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_kind_or_default_on_minimal_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_minimal_reference_element()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "ReferenceElement"
            / "on_minimal.json"
            / "kind_or_default.trace"
        )

        log = [tests.common.trace(instance.kind_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_category_or_default_on_complete_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_complete_reference_element()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "ReferenceElement"
            / "on_complete.json"
            / "category_or_default.trace"
        )

        log = [tests.common.trace(instance.category_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_category_or_default_on_minimal_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_minimal_reference_element()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "ReferenceElement"
            / "on_minimal.json"
            / "category_or_default.trace"
        )

        log = [tests.common.trace(instance.category_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)


class Test_Blob(unittest.TestCase):
    """
    Test ``X_or_default`` on instances of
    :py:class:`aas_core3_rc02.types.Blob`.
    """

    def test_kind_or_default_on_complete_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_complete_blob()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "Blob"
            / "on_complete.json"
            / "kind_or_default.trace"
        )

        log = [tests.common.trace(instance.kind_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_kind_or_default_on_minimal_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_minimal_blob()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "Blob"
            / "on_minimal.json"
            / "kind_or_default.trace"
        )

        log = [tests.common.trace(instance.kind_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_category_or_default_on_complete_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_complete_blob()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "Blob"
            / "on_complete.json"
            / "category_or_default.trace"
        )

        log = [tests.common.trace(instance.category_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_category_or_default_on_minimal_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_minimal_blob()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "Blob"
            / "on_minimal.json"
            / "category_or_default.trace"
        )

        log = [tests.common.trace(instance.category_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)


class Test_File(unittest.TestCase):
    """
    Test ``X_or_default`` on instances of
    :py:class:`aas_core3_rc02.types.File`.
    """

    def test_kind_or_default_on_complete_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_complete_file()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "File"
            / "on_complete.json"
            / "kind_or_default.trace"
        )

        log = [tests.common.trace(instance.kind_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_kind_or_default_on_minimal_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_minimal_file()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "File"
            / "on_minimal.json"
            / "kind_or_default.trace"
        )

        log = [tests.common.trace(instance.kind_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_category_or_default_on_complete_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_complete_file()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "File"
            / "on_complete.json"
            / "category_or_default.trace"
        )

        log = [tests.common.trace(instance.category_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_category_or_default_on_minimal_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_minimal_file()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "File"
            / "on_minimal.json"
            / "category_or_default.trace"
        )

        log = [tests.common.trace(instance.category_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)


class Test_AnnotatedRelationshipElement(unittest.TestCase):
    """
    Test ``X_or_default`` on instances of
    :py:class:`aas_core3_rc02.types.AnnotatedRelationshipElement`.
    """

    def test_kind_or_default_on_complete_instance_against_recorded(self) -> None:
        instance = (
            tests.common_jsonization.load_complete_annotated_relationship_element()
        )
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "AnnotatedRelationshipElement"
            / "on_complete.json"
            / "kind_or_default.trace"
        )

        log = [tests.common.trace(instance.kind_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_kind_or_default_on_minimal_instance_against_recorded(self) -> None:
        instance = (
            tests.common_jsonization.load_minimal_annotated_relationship_element()
        )
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "AnnotatedRelationshipElement"
            / "on_minimal.json"
            / "kind_or_default.trace"
        )

        log = [tests.common.trace(instance.kind_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)


class Test_Entity(unittest.TestCase):
    """
    Test ``X_or_default`` on instances of
    :py:class:`aas_core3_rc02.types.Entity`.
    """

    def test_kind_or_default_on_complete_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_complete_entity()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "Entity"
            / "on_complete.json"
            / "kind_or_default.trace"
        )

        log = [tests.common.trace(instance.kind_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_kind_or_default_on_minimal_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_minimal_entity()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "Entity"
            / "on_minimal.json"
            / "kind_or_default.trace"
        )

        log = [tests.common.trace(instance.kind_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)


class Test_BasicEventElement(unittest.TestCase):
    """
    Test ``X_or_default`` on instances of
    :py:class:`aas_core3_rc02.types.BasicEventElement`.
    """

    def test_kind_or_default_on_complete_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_complete_basic_event_element()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "BasicEventElement"
            / "on_complete.json"
            / "kind_or_default.trace"
        )

        log = [tests.common.trace(instance.kind_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_kind_or_default_on_minimal_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_minimal_basic_event_element()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "BasicEventElement"
            / "on_minimal.json"
            / "kind_or_default.trace"
        )

        log = [tests.common.trace(instance.kind_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)


class Test_Operation(unittest.TestCase):
    """
    Test ``X_or_default`` on instances of
    :py:class:`aas_core3_rc02.types.Operation`.
    """

    def test_kind_or_default_on_complete_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_complete_operation()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "Operation"
            / "on_complete.json"
            / "kind_or_default.trace"
        )

        log = [tests.common.trace(instance.kind_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_kind_or_default_on_minimal_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_minimal_operation()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "Operation"
            / "on_minimal.json"
            / "kind_or_default.trace"
        )

        log = [tests.common.trace(instance.kind_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)


class Test_Capability(unittest.TestCase):
    """
    Test ``X_or_default`` on instances of
    :py:class:`aas_core3_rc02.types.Capability`.
    """

    def test_kind_or_default_on_complete_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_complete_capability()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "Capability"
            / "on_complete.json"
            / "kind_or_default.trace"
        )

        log = [tests.common.trace(instance.kind_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_kind_or_default_on_minimal_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_minimal_capability()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "Capability"
            / "on_minimal.json"
            / "kind_or_default.trace"
        )

        log = [tests.common.trace(instance.kind_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)


class Test_ConceptDescription(unittest.TestCase):
    """
    Test ``X_or_default`` on instances of
    :py:class:`aas_core3_rc02.types.ConceptDescription`.
    """

    def test_category_or_default_on_complete_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_complete_concept_description()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "ConceptDescription"
            / "on_complete.json"
            / "category_or_default.trace"
        )

        log = [tests.common.trace(instance.category_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_category_or_default_on_minimal_instance_against_recorded(self) -> None:
        instance = tests.common_jsonization.load_minimal_concept_description()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "test_X_or_default"
            / "ConceptDescription"
            / "on_minimal.json"
            / "category_or_default.trace"
        )

        log = [tests.common.trace(instance.category_or_default())]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)


if __name__ == "__main__":
    unittest.main()


# This code has been automatically generated by:
# dev_scripts/generate_test_for_x_or_default.py
# Do NOT edit or append.
