# This code has been automatically generated by:
# dev_scripts/generate_test_for_descend_and_pass_through_visitor.py
# Do NOT edit or append.


"""
Test jointly :py:method:`aas_core3_rc02.types.Class.descend` and
:py:method:`aas_core3_rc02.types.PassThroughVisitor`.
"""


# pylint: disable=missing-docstring


from typing import (
    List,
    Sequence,
)
import unittest

import aas_core3_rc02.types as aas_types

import tests.common
import tests.common_jsonization


class _TracingVisitor(aas_types.PassThroughVisitor):
    """Visit the instances and trace them."""

    def __init__(self) -> None:
        """Initialize with an empty log."""
        self._log = []  # type: List[str]

    @property
    def log(self) -> Sequence[str]:
        """Get the tracing log."""
        return self._log

    def visit(self, that: aas_types.Class) -> None:
        self._log.append(tests.common.trace(that))
        super().visit(that)


def assert_tracing_logs_from_descend_and_visitor_are_the_same(
    that: aas_types.Class, test_case: unittest.TestCase
) -> None:
    """
    Check that the tracing logs are the same when :paramref:`that` instance
    is visited and when :paramref:`that` is ran through
    :py:method:`aas_types.Class.descend`.

    :param that: instance to be iterated over
    :param test_case: in which this assertion runs
    :raise: :py:class:`AssertionError` if the logs differ
    """
    log_from_descend = [tests.common.trace(something) for something in that.descend()]

    visitor = _TracingVisitor()
    visitor.visit(that)
    log_from_visitor = visitor.log

    test_case.assertGreater(len(log_from_visitor), 0)
    test_case.assertEqual(tests.common.trace(that), log_from_visitor[0])

    # noinspection PyTypeChecker
    test_case.assertListEqual(log_from_descend, log_from_visitor[1:])  # type: ignore


class Test_Extension(unittest.TestCase):
    def test_descend_against_recorded_trace_log(self) -> None:
        instance = tests.common_jsonization.load_complete_extension()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "descend_and_pass_through_visitor"
            / "Extension"
            / "complete.json.trace"
        )

        log = [tests.common.trace(something) for something in instance.descend()]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_descend_against_visitor(self) -> None:
        instance = tests.common_jsonization.load_complete_extension()
        assert_tracing_logs_from_descend_and_visitor_are_the_same(instance, self)


class Test_AdministrativeInformation(unittest.TestCase):
    def test_descend_against_recorded_trace_log(self) -> None:
        instance = tests.common_jsonization.load_complete_administrative_information()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "descend_and_pass_through_visitor"
            / "AdministrativeInformation"
            / "complete.json.trace"
        )

        log = [tests.common.trace(something) for something in instance.descend()]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_descend_against_visitor(self) -> None:
        instance = tests.common_jsonization.load_complete_administrative_information()
        assert_tracing_logs_from_descend_and_visitor_are_the_same(instance, self)


class Test_Qualifier(unittest.TestCase):
    def test_descend_against_recorded_trace_log(self) -> None:
        instance = tests.common_jsonization.load_complete_qualifier()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "descend_and_pass_through_visitor"
            / "Qualifier"
            / "complete.json.trace"
        )

        log = [tests.common.trace(something) for something in instance.descend()]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_descend_against_visitor(self) -> None:
        instance = tests.common_jsonization.load_complete_qualifier()
        assert_tracing_logs_from_descend_and_visitor_are_the_same(instance, self)


class Test_AssetAdministrationShell(unittest.TestCase):
    def test_descend_against_recorded_trace_log(self) -> None:
        instance = tests.common_jsonization.load_complete_asset_administration_shell()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "descend_and_pass_through_visitor"
            / "AssetAdministrationShell"
            / "complete.json.trace"
        )

        log = [tests.common.trace(something) for something in instance.descend()]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_descend_against_visitor(self) -> None:
        instance = tests.common_jsonization.load_complete_asset_administration_shell()
        assert_tracing_logs_from_descend_and_visitor_are_the_same(instance, self)


class Test_AssetInformation(unittest.TestCase):
    def test_descend_against_recorded_trace_log(self) -> None:
        instance = tests.common_jsonization.load_complete_asset_information()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "descend_and_pass_through_visitor"
            / "AssetInformation"
            / "complete.json.trace"
        )

        log = [tests.common.trace(something) for something in instance.descend()]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_descend_against_visitor(self) -> None:
        instance = tests.common_jsonization.load_complete_asset_information()
        assert_tracing_logs_from_descend_and_visitor_are_the_same(instance, self)


class Test_Resource(unittest.TestCase):
    def test_descend_against_recorded_trace_log(self) -> None:
        instance = tests.common_jsonization.load_complete_resource()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "descend_and_pass_through_visitor"
            / "Resource"
            / "complete.json.trace"
        )

        log = [tests.common.trace(something) for something in instance.descend()]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_descend_against_visitor(self) -> None:
        instance = tests.common_jsonization.load_complete_resource()
        assert_tracing_logs_from_descend_and_visitor_are_the_same(instance, self)


class Test_SpecificAssetId(unittest.TestCase):
    def test_descend_against_recorded_trace_log(self) -> None:
        instance = tests.common_jsonization.load_complete_specific_asset_id()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "descend_and_pass_through_visitor"
            / "SpecificAssetId"
            / "complete.json.trace"
        )

        log = [tests.common.trace(something) for something in instance.descend()]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_descend_against_visitor(self) -> None:
        instance = tests.common_jsonization.load_complete_specific_asset_id()
        assert_tracing_logs_from_descend_and_visitor_are_the_same(instance, self)


class Test_Submodel(unittest.TestCase):
    def test_descend_against_recorded_trace_log(self) -> None:
        instance = tests.common_jsonization.load_complete_submodel()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "descend_and_pass_through_visitor"
            / "Submodel"
            / "complete.json.trace"
        )

        log = [tests.common.trace(something) for something in instance.descend()]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_descend_against_visitor(self) -> None:
        instance = tests.common_jsonization.load_complete_submodel()
        assert_tracing_logs_from_descend_and_visitor_are_the_same(instance, self)


class Test_RelationshipElement(unittest.TestCase):
    def test_descend_against_recorded_trace_log(self) -> None:
        instance = tests.common_jsonization.load_complete_relationship_element()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "descend_and_pass_through_visitor"
            / "RelationshipElement"
            / "complete.json.trace"
        )

        log = [tests.common.trace(something) for something in instance.descend()]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_descend_against_visitor(self) -> None:
        instance = tests.common_jsonization.load_complete_relationship_element()
        assert_tracing_logs_from_descend_and_visitor_are_the_same(instance, self)


class Test_SubmodelElementList(unittest.TestCase):
    def test_descend_against_recorded_trace_log(self) -> None:
        instance = tests.common_jsonization.load_complete_submodel_element_list()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "descend_and_pass_through_visitor"
            / "SubmodelElementList"
            / "complete.json.trace"
        )

        log = [tests.common.trace(something) for something in instance.descend()]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_descend_against_visitor(self) -> None:
        instance = tests.common_jsonization.load_complete_submodel_element_list()
        assert_tracing_logs_from_descend_and_visitor_are_the_same(instance, self)


class Test_SubmodelElementCollection(unittest.TestCase):
    def test_descend_against_recorded_trace_log(self) -> None:
        instance = tests.common_jsonization.load_complete_submodel_element_collection()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "descend_and_pass_through_visitor"
            / "SubmodelElementCollection"
            / "complete.json.trace"
        )

        log = [tests.common.trace(something) for something in instance.descend()]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_descend_against_visitor(self) -> None:
        instance = tests.common_jsonization.load_complete_submodel_element_collection()
        assert_tracing_logs_from_descend_and_visitor_are_the_same(instance, self)


class Test_Property(unittest.TestCase):
    def test_descend_against_recorded_trace_log(self) -> None:
        instance = tests.common_jsonization.load_complete_property()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "descend_and_pass_through_visitor"
            / "Property"
            / "complete.json.trace"
        )

        log = [tests.common.trace(something) for something in instance.descend()]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_descend_against_visitor(self) -> None:
        instance = tests.common_jsonization.load_complete_property()
        assert_tracing_logs_from_descend_and_visitor_are_the_same(instance, self)


class Test_MultiLanguageProperty(unittest.TestCase):
    def test_descend_against_recorded_trace_log(self) -> None:
        instance = tests.common_jsonization.load_complete_multi_language_property()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "descend_and_pass_through_visitor"
            / "MultiLanguageProperty"
            / "complete.json.trace"
        )

        log = [tests.common.trace(something) for something in instance.descend()]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_descend_against_visitor(self) -> None:
        instance = tests.common_jsonization.load_complete_multi_language_property()
        assert_tracing_logs_from_descend_and_visitor_are_the_same(instance, self)


class Test_Range(unittest.TestCase):
    def test_descend_against_recorded_trace_log(self) -> None:
        instance = tests.common_jsonization.load_complete_range()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "descend_and_pass_through_visitor"
            / "Range"
            / "complete.json.trace"
        )

        log = [tests.common.trace(something) for something in instance.descend()]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_descend_against_visitor(self) -> None:
        instance = tests.common_jsonization.load_complete_range()
        assert_tracing_logs_from_descend_and_visitor_are_the_same(instance, self)


class Test_ReferenceElement(unittest.TestCase):
    def test_descend_against_recorded_trace_log(self) -> None:
        instance = tests.common_jsonization.load_complete_reference_element()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "descend_and_pass_through_visitor"
            / "ReferenceElement"
            / "complete.json.trace"
        )

        log = [tests.common.trace(something) for something in instance.descend()]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_descend_against_visitor(self) -> None:
        instance = tests.common_jsonization.load_complete_reference_element()
        assert_tracing_logs_from_descend_and_visitor_are_the_same(instance, self)


class Test_Blob(unittest.TestCase):
    def test_descend_against_recorded_trace_log(self) -> None:
        instance = tests.common_jsonization.load_complete_blob()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "descend_and_pass_through_visitor"
            / "Blob"
            / "complete.json.trace"
        )

        log = [tests.common.trace(something) for something in instance.descend()]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_descend_against_visitor(self) -> None:
        instance = tests.common_jsonization.load_complete_blob()
        assert_tracing_logs_from_descend_and_visitor_are_the_same(instance, self)


class Test_File(unittest.TestCase):
    def test_descend_against_recorded_trace_log(self) -> None:
        instance = tests.common_jsonization.load_complete_file()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "descend_and_pass_through_visitor"
            / "File"
            / "complete.json.trace"
        )

        log = [tests.common.trace(something) for something in instance.descend()]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_descend_against_visitor(self) -> None:
        instance = tests.common_jsonization.load_complete_file()
        assert_tracing_logs_from_descend_and_visitor_are_the_same(instance, self)


class Test_AnnotatedRelationshipElement(unittest.TestCase):
    def test_descend_against_recorded_trace_log(self) -> None:
        instance = (
            tests.common_jsonization.load_complete_annotated_relationship_element()
        )
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "descend_and_pass_through_visitor"
            / "AnnotatedRelationshipElement"
            / "complete.json.trace"
        )

        log = [tests.common.trace(something) for something in instance.descend()]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_descend_against_visitor(self) -> None:
        instance = (
            tests.common_jsonization.load_complete_annotated_relationship_element()
        )
        assert_tracing_logs_from_descend_and_visitor_are_the_same(instance, self)


class Test_Entity(unittest.TestCase):
    def test_descend_against_recorded_trace_log(self) -> None:
        instance = tests.common_jsonization.load_complete_entity()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "descend_and_pass_through_visitor"
            / "Entity"
            / "complete.json.trace"
        )

        log = [tests.common.trace(something) for something in instance.descend()]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_descend_against_visitor(self) -> None:
        instance = tests.common_jsonization.load_complete_entity()
        assert_tracing_logs_from_descend_and_visitor_are_the_same(instance, self)


class Test_EventPayload(unittest.TestCase):
    def test_descend_against_recorded_trace_log(self) -> None:
        instance = tests.common_jsonization.load_complete_event_payload()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "descend_and_pass_through_visitor"
            / "EventPayload"
            / "complete.json.trace"
        )

        log = [tests.common.trace(something) for something in instance.descend()]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_descend_against_visitor(self) -> None:
        instance = tests.common_jsonization.load_complete_event_payload()
        assert_tracing_logs_from_descend_and_visitor_are_the_same(instance, self)


class Test_BasicEventElement(unittest.TestCase):
    def test_descend_against_recorded_trace_log(self) -> None:
        instance = tests.common_jsonization.load_complete_basic_event_element()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "descend_and_pass_through_visitor"
            / "BasicEventElement"
            / "complete.json.trace"
        )

        log = [tests.common.trace(something) for something in instance.descend()]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_descend_against_visitor(self) -> None:
        instance = tests.common_jsonization.load_complete_basic_event_element()
        assert_tracing_logs_from_descend_and_visitor_are_the_same(instance, self)


class Test_Operation(unittest.TestCase):
    def test_descend_against_recorded_trace_log(self) -> None:
        instance = tests.common_jsonization.load_complete_operation()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "descend_and_pass_through_visitor"
            / "Operation"
            / "complete.json.trace"
        )

        log = [tests.common.trace(something) for something in instance.descend()]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_descend_against_visitor(self) -> None:
        instance = tests.common_jsonization.load_complete_operation()
        assert_tracing_logs_from_descend_and_visitor_are_the_same(instance, self)


class Test_OperationVariable(unittest.TestCase):
    def test_descend_against_recorded_trace_log(self) -> None:
        instance = tests.common_jsonization.load_complete_operation_variable()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "descend_and_pass_through_visitor"
            / "OperationVariable"
            / "complete.json.trace"
        )

        log = [tests.common.trace(something) for something in instance.descend()]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_descend_against_visitor(self) -> None:
        instance = tests.common_jsonization.load_complete_operation_variable()
        assert_tracing_logs_from_descend_and_visitor_are_the_same(instance, self)


class Test_Capability(unittest.TestCase):
    def test_descend_against_recorded_trace_log(self) -> None:
        instance = tests.common_jsonization.load_complete_capability()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "descend_and_pass_through_visitor"
            / "Capability"
            / "complete.json.trace"
        )

        log = [tests.common.trace(something) for something in instance.descend()]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_descend_against_visitor(self) -> None:
        instance = tests.common_jsonization.load_complete_capability()
        assert_tracing_logs_from_descend_and_visitor_are_the_same(instance, self)


class Test_ConceptDescription(unittest.TestCase):
    def test_descend_against_recorded_trace_log(self) -> None:
        instance = tests.common_jsonization.load_complete_concept_description()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "descend_and_pass_through_visitor"
            / "ConceptDescription"
            / "complete.json.trace"
        )

        log = [tests.common.trace(something) for something in instance.descend()]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_descend_against_visitor(self) -> None:
        instance = tests.common_jsonization.load_complete_concept_description()
        assert_tracing_logs_from_descend_and_visitor_are_the_same(instance, self)


class Test_Reference(unittest.TestCase):
    def test_descend_against_recorded_trace_log(self) -> None:
        instance = tests.common_jsonization.load_complete_reference()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "descend_and_pass_through_visitor"
            / "Reference"
            / "complete.json.trace"
        )

        log = [tests.common.trace(something) for something in instance.descend()]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_descend_against_visitor(self) -> None:
        instance = tests.common_jsonization.load_complete_reference()
        assert_tracing_logs_from_descend_and_visitor_are_the_same(instance, self)


class Test_Key(unittest.TestCase):
    def test_descend_against_recorded_trace_log(self) -> None:
        instance = tests.common_jsonization.load_complete_key()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "descend_and_pass_through_visitor"
            / "Key"
            / "complete.json.trace"
        )

        log = [tests.common.trace(something) for something in instance.descend()]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_descend_against_visitor(self) -> None:
        instance = tests.common_jsonization.load_complete_key()
        assert_tracing_logs_from_descend_and_visitor_are_the_same(instance, self)


class Test_LangString(unittest.TestCase):
    def test_descend_against_recorded_trace_log(self) -> None:
        instance = tests.common_jsonization.load_complete_lang_string()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "descend_and_pass_through_visitor"
            / "LangString"
            / "complete.json.trace"
        )

        log = [tests.common.trace(something) for something in instance.descend()]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_descend_against_visitor(self) -> None:
        instance = tests.common_jsonization.load_complete_lang_string()
        assert_tracing_logs_from_descend_and_visitor_are_the_same(instance, self)


class Test_Environment(unittest.TestCase):
    def test_descend_against_recorded_trace_log(self) -> None:
        instance = tests.common_jsonization.load_complete_environment()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "descend_and_pass_through_visitor"
            / "Environment"
            / "complete.json.trace"
        )

        log = [tests.common.trace(something) for something in instance.descend()]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_descend_against_visitor(self) -> None:
        instance = tests.common_jsonization.load_complete_environment()
        assert_tracing_logs_from_descend_and_visitor_are_the_same(instance, self)


class Test_EmbeddedDataSpecification(unittest.TestCase):
    def test_descend_against_recorded_trace_log(self) -> None:
        instance = tests.common_jsonization.load_complete_embedded_data_specification()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "descend_and_pass_through_visitor"
            / "EmbeddedDataSpecification"
            / "complete.json.trace"
        )

        log = [tests.common.trace(something) for something in instance.descend()]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_descend_against_visitor(self) -> None:
        instance = tests.common_jsonization.load_complete_embedded_data_specification()
        assert_tracing_logs_from_descend_and_visitor_are_the_same(instance, self)


class Test_ValueReferencePair(unittest.TestCase):
    def test_descend_against_recorded_trace_log(self) -> None:
        instance = tests.common_jsonization.load_complete_value_reference_pair()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "descend_and_pass_through_visitor"
            / "ValueReferencePair"
            / "complete.json.trace"
        )

        log = [tests.common.trace(something) for something in instance.descend()]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_descend_against_visitor(self) -> None:
        instance = tests.common_jsonization.load_complete_value_reference_pair()
        assert_tracing_logs_from_descend_and_visitor_are_the_same(instance, self)


class Test_ValueList(unittest.TestCase):
    def test_descend_against_recorded_trace_log(self) -> None:
        instance = tests.common_jsonization.load_complete_value_list()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "descend_and_pass_through_visitor"
            / "ValueList"
            / "complete.json.trace"
        )

        log = [tests.common.trace(something) for something in instance.descend()]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_descend_against_visitor(self) -> None:
        instance = tests.common_jsonization.load_complete_value_list()
        assert_tracing_logs_from_descend_and_visitor_are_the_same(instance, self)


class Test_DataSpecificationIEC61360(unittest.TestCase):
    def test_descend_against_recorded_trace_log(self) -> None:
        instance = tests.common_jsonization.load_complete_data_specification_iec_61360()
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "descend_and_pass_through_visitor"
            / "DataSpecificationIEC61360"
            / "complete.json.trace"
        )

        log = [tests.common.trace(something) for something in instance.descend()]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_descend_against_visitor(self) -> None:
        instance = tests.common_jsonization.load_complete_data_specification_iec_61360()
        assert_tracing_logs_from_descend_and_visitor_are_the_same(instance, self)


class Test_DataSpecificationPhysicalUnit(unittest.TestCase):
    def test_descend_against_recorded_trace_log(self) -> None:
        instance = (
            tests.common_jsonization.load_complete_data_specification_physical_unit()
        )
        expected_path = (
            tests.common.TEST_DATA_DIR
            / "descend_and_pass_through_visitor"
            / "DataSpecificationPhysicalUnit"
            / "complete.json.trace"
        )

        log = [tests.common.trace(something) for something in instance.descend()]
        got_text = tests.common.trace_log_as_text_file_content(log)
        tests.common.record_or_check(expected_path, got_text)

    def test_descend_against_visitor(self) -> None:
        instance = (
            tests.common_jsonization.load_complete_data_specification_physical_unit()
        )
        assert_tracing_logs_from_descend_and_visitor_are_the_same(instance, self)


if __name__ == "__main__":
    unittest.main()


# This code has been automatically generated by:
# dev_scripts/generate_test_for_descend_and_pass_through_visitor.py
# Do NOT edit or append.
